---

var_lib_docker_device: /dev/xvdf

concourse_worker: yes
# Don't start as we don't want worker to start during the build
concourse_worker_name: "$(hostname)"
concourse_service_enabled: no
concourse_worker_options: |
  --garden-network-pool 10.254.0.0/16 \
  --garden-max-containers 1024 \
  --garden-log-level=error \
  --baggageclaim-log-level=error \
  --garden-assets-dir=/var/lib/docker/garden_assets/ \
  --garden-depot=/var/lib/docker/garden_depot \
  --baggageclaim-volumes=/var/lib/docker/baggageclaim_volumes \
  --baggageclaim-driver=btrfs | tee -a /var/log/concourse-worker.log

  #--garden-default-grace-time=120s \
  #--garden-graph=/var/lib/docker/garden_graph \

#--garden-cleanup-process-dirs-on-wait=true
#--garden-destroy-containers-on-startup=true


concourse_install_dir: /var/lib/concourse
concourse_work_dir: /var/lib/docker/concourse

logrotate_scripts:
  - name: concourse-worker
    path: "/var/log/concourse-worker.log"
    options:
      - rotate 2
      - daily
      - missingok
      - compress
      - delaycompress
      - copytruncate

cycloid_files_watched:
 - name: concourse-worker
   path: "/var/log/concourse-worker.log"


sysctl_configs:
  - name: net.ipv4.ip_forward
    value: 1
  - name: net.nf_conntrack_max
    value: 524288

  # https://access.redhat.com/solutions/726753
  - name: net.ipv4.tcp_retries2
    value: 8

  #  We can't change the local_port_range without changing the NodePort range
  # "# Allowed local port range",
  - name: net.ipv4.ip_local_port_range
    value: "32768    65535"

  #- name: net.ipv4.tcp_max_tw_buckets
  #  value: 2000000

  #  Increase the number of connections
  - name: net.core.somaxconn
    value: 32768

  # Maximum Socket Receive Buffer
  - name: net.core.rmem_max
    value: 16777216

  # Default Socket Send Buffer
  - name: net.core.wmem_max
    value: 16777216

  # Increase the maximum total buffer-space allocatable
  - name: net.ipv4.tcp_wmem
    value: "4096 12582912 16777216"
  - name: net.ipv4.tcp_rmem
    value: "4096 12582912 16777216"


   # Increase the number of outstanding syn requests allowed
  - name: net.ipv4.tcp_max_syn_backlog
    value: 8096

   # Max number of packets that can be queued on interface input",
   # If kernel is receiving packets faster than can be processed",
   # this queue increases",
  - name: net.core.netdev_max_backlog
    value: 16384

   # Increase size of file handles and inode cache",
  - name: fs.file-max
    value: 2097152

  # Max number of inotify instances and watches for a user",
  # Since dockerd runs as a single user, the default instances value of 128 per user is too low",
  # e.g. uses of inotify: nginx ingress controller, kubectl logs -f",
  - name: fs.inotify.max_user_instances
    value: 8192
  - name: fs.inotify.max_user_watches
    value: 524288

  #  A higher vm.max_map_count is great for elasticsearch, mongo, or other mmap users
  #  See https://github.com/kubernetes/kops/issues/1340
  - name: vm.max_map_count
    value: 262144

# This var is sent by the pipeline
# concourse_version: 3.9.2

#
# Require override
#

#concourse_tsa_host: "have to be set"
#concourse_tsa_public_key: "pub_key"
#concourse_tsa_worker_key: "worker key"
