---

- hosts: localhost
  connection: local
  remote_user: root
  become: yes
  vars_files:
    - "default.yml"
    - [ "{{ env }}-worker.yml", "empty.yml" ]
  tasks:

    - name: not mount xvdg by cloudinit
      blockinfile:
        path: /etc/cloud/cloud.cfg
        block: |
          mounts:
          - [ ephemeral0, null ]
          fs_setup:
             - label: ephemeral0
               filesystem: '{{ fs_volume_type }}'
               device: 'ephemeral0'
               partition: 'none'
               overwrite: True
      when: ansible_system_vendor == "Amazon EC2" and (var_lib_device != "nodevice")

    - name: Ensure admin user is present
      user:
        name: admin
        state: present
        create_home: true
      when: ansible_version.major != 2 or ansible_version.minor > 4
    - name: Ensure admin user is present (2.4 compact)
      user:
        name: admin
        state: present
        createhome: true
      when: ansible_version.major == 2 and ansible_version.minor < 5

    - template:
        src: first-boot.yml.tpl
        dest: /home/admin/first-boot.yml
        owner: admin
        group: admin
    
    - block:
      - template:
          src: user-data.sh.scw.tpl
          dest: /home/admin/user-data.sh
          owner: admin
          group: admin
        when: ansible_system_vendor == "Scaleway"
      - template:
          src: user-data.sh.tpl
          dest: /home/admin/user-data.sh
          owner: admin
          group: admin
        when: ansible_system_vendor != "Scaleway"

    # Generate the ansible hosts file like https://www.packer.io/docs/provisioners/ansible-local.html#inventory_groups do.
    # We do that because we need this inventory file for post ansible run to deploy the code when the AWS instance boot
    - name: Ensure /etc/ansible/hosts is flushed
      file: state=absent path=/etc/ansible/hosts

    - name: Generate /etc/ansible/hosts
      lineinfile: dest=/etc/ansible/hosts regexp="^\[{{ item }}\]" line='[{{ item }}]\n127.0.0.1\n' create=true
      with_items: "{{ groups }}"
