- src: https://github.com/cycloidio/ansible-telegraf
  version: master
  name: cycloid.telegraf
  scm: git

- src: https://github.com/dj-wasabi/ansible-telegraf
  version: master
  name: dj-wasabi.telegraf
  scm: git

- src: https://github.com/cycloidio/ansible-concourse
  version: master
  name: cycloid.concourse
  scm: git

- src: https://github.com/geerlingguy/ansible-role-docker
  version: master
  name: geerlingguy.docker
  scm: git

- src: https://github.com/cycloidio/ansible-systemd
  version: master
  name: cycloid.systemd
  scm: git

- src: https://github.com/cycloidio/ansible-fluentd
  version: master
  name: cycloid.fluentd
  scm: git

- src: https://github.com/nickhammond/ansible-logrotate
  version: master
  name: nickhammond.ansible-logrotate
  scm: git
